version: "3.4"

networks:
  scrapy:

services:
  splash:
    image: scrapinghub/splash:master
    command: --maxrss 4000
    restart: always
    ports:
      - "127.0.0.1:8050:8050"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/_ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
  headless_chrome:
    image: ghcr.io/browserless/chromium:v2.14.0
    restart: always
    environment:
      - TIMEOUT=120000
    ports:
      - "127.0.0.1:3000:3000"
