FROM python:3.12.5-slim-bookworm

RUN apt-get install ca-certificates

WORKDIR /oeh-search-etl

COPY edu_sharing_openapi/ edu_sharing_openapi/
COPY pyproject.toml poetry.lock ./
RUN pip3 install --no-cache-dir poetry && poetry install

COPY . .
COPY .env.docker .env

CMD [ "bash", "-c", "poetry run python run.py" ]
