FROM python:3.13-slim-bookworm

ENV TZ="Europe/Berlin"

RUN apt-get install ca-certificates

WORKDIR /oeh-search-etl

COPY edu_sharing_openapi/ edu_sharing_openapi/
COPY pyproject.toml poetry.lock Readme.md ./
RUN pip3 install --no-cache-dir poetry && poetry install

COPY . .
COPY ./schulcloud/edusharing_setup.py ./edusharing_setup.py

CMD [ "bash", "-c", "poetry run python edusharing_setup.py" ]
