FROM python:3.11.6-slim-bookworm

RUN apt-get install ca-certificates

WORKDIR /oeh-search-etl

COPY requirements.txt .
RUN python3.11 -m pip install --no-cache-dir -r requirements.txt

COPY . .
COPY .env.docker .env

CMD [ "bash", "-c", "python3.11 run.py" ]
