name: Release Helm Charts

on: push
    # branches:
    #   - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # https://github.com/helm/chart-releaser-action
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
            charts_dir: charts
            # make it a a universal variable/secret?
            charts_repo_url: https://hpi-schul-cloud.github.io/helm-charts-registry/
        env:
          CR_TOKEN: "${{ secrets.REPO_ACCESS_TOKEN }}"
